### PR TITLE
Garlic tacos

### PR DESCRIPTION
**Pull request by astuke**
Added garlic to taco recipe.

### CODE REVIEW

**Review by jenswehnerteaching — COMMENTED** [review]
Thanks does this relate to https://github.com/jenswehnerteaching/forking/issues/4 ? 

This seems unrelated.

**Comment by astuke** [comment]
Oh I see, so in my commit message I should've referenced to the issue which I opened earlier? Yes, #4

**Comment by jenswehnerteaching** [comment]
@astuke  Not required, but it is good form. :)

**Review by jenswehnerteaching — APPROVED** [review]
Thanks merging now

**Pull request merged**
